import Head from "next/head";
import Header from "../header/header";

const Layout = ({main, children}) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!main ? <Header className="container" /> : ``}


      <main>
        <h1 className="visually-hidden"></h1>
        {children}
      </main>
    </>
  );
};

export default Layout;
