import Head from "next/head";
import Footer from "../footer/footer";
import Header from "../header/header";
import layoutStyle from "./layout.module.css";

const Layout = ({main, children, content}) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
        <meta name="viewport" content="width=1024, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={layoutStyle.layout}>
        {!main ? <Header className="container" /> : null}

        <main className={layoutStyle.main}>
          <h1 className="visually-hidden"></h1>
          {children}
        </main>

        <Footer className="container" content={content.footer} />
      </div>
    </>
  );
};

export default Layout;
